# Generated by Django 4.2.19 on 2025-02-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='event_name',
        ),
    ]
